---
# tasks file for ansible-nexus
- name: download Nexus to host
  local_action: get_url url=http://download.sonatype.com/nexus/oss/{{nexus_package}} dest="{{nexus_download_dir}}/{{nexus_package}}"
  tags: download
  sudo: no

- name: "{{nexus_installation_dir}} must exist"
  file:
    path="{{nexus_installation_dir}}"
    state="directory"

- name: Unpacks Nexus download
  unarchive:
    src="{{nexus_download_dir}}/{{nexus_package}}"
    dest="{{nexus_installation_dir}}"
    creates="{{nexus_installation_dir}}/nexus-{{nexus_version}}/bin/nexus"
    force=no
  tags: unpack

- name: Move sonatype working directory into place (1/2)
  stat: path="{{nexus_installation_dir}}/sonatype-work"
  register: s_w

- name: Move sonatype working directory into place (2/2)
  command: mv "{{nexus_installation_dir}}/sonatype-work" "{{nexus_working_dir}}"
  when: s_w.stat.exists

- name: Configure port
  lineinfile:
    dest="{{nexus_installation_dir}}/nexus-{{nexus_version}}/conf/nexus.properties"
    line="application-port={{nexus_port}}"
    regexp="application-port=.*"
    state=present

- name: Configure workdir
  lineinfile:
    dest="{{nexus_installation_dir}}/nexus-{{nexus_version}}/conf/nexus.properties"
    line="nexus-work={{nexus_working_dir}}"
    regexp="nexus-work=.*"
    state=present
